name: Linting and style checking

on: 
  workflow_dispatch:
  pull_request:

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --color always --check lua/
          # Specify `version` to pin a specific version, otherwise action will always use latest version/automatically update
          version: latest
